"""
ExerciseLibrary – Persistent library of math exercises.

Analogous to BuggyRuleLearner: exercises generated by the LLM are stored,
progressively validated, and reused without LLM cost.
"""

import hashlib
import json
import logging
import os
import time
from typing import Dict, Any, List, Optional

from core.persistence import SQLiteStore

logger = logging.getLogger(__name__)

DEFAULT_LIBRARY_PATH = os.path.join(os.path.dirname(__file__), "exercise_library.db")
MIN_USAGE_FOR_AUTO_PROMOTION = 3


class ExerciseLibrary(SQLiteStore):
    """
    Manages an exercise library with metadata, search, and validation.
    """

    _TABLE = "exercises"
    _PK = "id"
    _COLUMNS = [
        "id", "concept", "difficulty", "problem_latex", "correct_latex",
        "steps", "hint", "source", "validated", "sympy_verified",
        "sympy_verify_detail", "usage_count", "document_context", "created_at",
    ]
    _CREATE_SQL = """
        CREATE TABLE IF NOT EXISTS exercises (
            id TEXT PRIMARY KEY,
            concept TEXT NOT NULL DEFAULT 'generic',
            difficulty TEXT NOT NULL DEFAULT 'medium',
            problem_latex TEXT NOT NULL DEFAULT '',
            correct_latex TEXT NOT NULL DEFAULT '',
            steps TEXT NOT NULL DEFAULT '[]',
            hint TEXT NOT NULL DEFAULT '',
            source TEXT NOT NULL DEFAULT 'llm',
            validated INTEGER NOT NULL DEFAULT 0,
            sympy_verified INTEGER DEFAULT NULL,
            sympy_verify_detail TEXT NOT NULL DEFAULT '',
            usage_count INTEGER NOT NULL DEFAULT 0,
            document_context TEXT NOT NULL DEFAULT '',
            created_at REAL NOT NULL DEFAULT 0
        )
    """

    def __init__(self, storage_path: Optional[str] = None):
        raw_path = storage_path or DEFAULT_LIBRARY_PATH
        if raw_path.endswith(".json"):
            raw_path = raw_path[:-5] + ".db"
        super().__init__(raw_path)
        self._exercises: Dict[str, Dict[str, Any]] = {}
        self._ensure_table(self._CREATE_SQL)
        self._maybe_migrate_json_legacy()
        self._load()

    def _maybe_migrate_json_legacy(self) -> None:
        json_path = self.storage_path[:-3] + ".json" if self.storage_path.endswith(".db") else self.storage_path + ".json"
        self._migrate_json(json_path, lambda item: self._upsert_item(self._normalize_exercise(item)))

    def _upsert_item(self, ex: Dict[str, Any]) -> None:
        self._upsert(
            self._TABLE,
            self._COLUMNS,
            self._PK,
            (
                ex["id"], ex["concept"], ex["difficulty"], ex["problem_latex"],
                ex["correct_latex"], json.dumps(ex["steps"]), ex["hint"], ex["source"],
                int(ex["validated"]), int(ex["sympy_verified"]) if ex["sympy_verified"] is not None else None,
                ex.get("sympy_verify_detail", ""), ex["usage_count"],
                ex["document_context"], ex["created_at"],
            ),
        )

    def _load(self):
        for row in self._fetch_all(self._TABLE):
            ex = dict(row)
            ex["validated"] = bool(ex["validated"])
            sv = ex["sympy_verified"]
            ex["sympy_verified"] = bool(sv) if sv is not None else None
            ex["steps"] = json.loads(ex["steps"]) if ex["steps"] else []
            self._exercises[ex["id"]] = ex
        logger.info("Loaded %d exercise(s) from %s", len(self._exercises), self.storage_path)

    def persist(self):
        try:
            for ex in self._exercises.values():
                self._upsert_item(ex)
            logger.info("Persisted %d exercise(s)", len(self._exercises))
        except Exception as exc:
            logger.error("Failed to persist exercise library: %s", exc)

    # ── Helpers ────────────────────────────────────────────────────────────

    @staticmethod
    def hash_exercise(problem_latex: str) -> str:
        """Generates a stable ID from the LaTeX problem."""
        return hashlib.sha256(problem_latex.strip().encode("utf-8")).hexdigest()[:16]

    @staticmethod
    def _normalize_exercise(ex: Dict[str, Any]) -> Dict[str, Any]:
        """Ensures consistency of required fields."""
        return {
            "id": ex.get("id", ExerciseLibrary.hash_exercise(ex.get("problem_latex", ""))),
            "concept": ex.get("concept", "generic"),
            "difficulty": ex.get("difficulty", "medium"),
            "problem_latex": ex.get("problem_latex", ""),
            "correct_latex": ex.get("correct_latex", ""),
            "steps": ex.get("steps", []),
            "hint": ex.get("hint", ""),
            "source": ex.get("source", "llm"),
            "validated": ex.get("validated", False),
            "sympy_verified": ex.get("sympy_verified", None),
            "usage_count": ex.get("usage_count", 0),
            "document_context": ex.get("document_context", ""),
            "created_at": ex.get("created_at", time.time()),
        }

    # ── CRUD ───────────────────────────────────────────────────────────────

    def add(self, exercise: Dict[str, Any], source: str = "llm") -> Dict[str, Any]:
        """
        Adds an exercise to the library. If the exercise already exists (same
        problem_latex), increments usage_count and returns the existing one.
        """
        ex = self._normalize_exercise(exercise)
        ex["source"] = source
        ex_id = ex["id"]

        if ex_id in self._exercises:
            self._exercises[ex_id]["usage_count"] += 1
            self._auto_promote(ex_id)
            self.persist()
            logger.debug("Exercise %s already exists, usage_count=%d", ex_id, self._exercises[ex_id]["usage_count"])
            return self._exercises[ex_id]

        ex["usage_count"] = 1
        self._exercises[ex_id] = ex
        self.persist()
        logger.info("Added exercise %s (concept=%s, source=%s)", ex_id, ex["concept"], source)
        return ex

    def get(self, ex_id: str) -> Optional[Dict[str, Any]]:
        return self._exercises.get(ex_id)

    def remove(self, ex_id: str) -> bool:
        if ex_id in self._exercises:
            del self._exercises[ex_id]
            self.persist()
            return True
        return False

    def validate(self, ex_id: str) -> bool:
        """Manual validation of an exercise."""
        if ex_id not in self._exercises:
            return False
        self._exercises[ex_id]["validated"] = True
        self._exercises[ex_id]["usage_count"] = max(
            self._exercises[ex_id].get("usage_count", 0),
            MIN_USAGE_FOR_AUTO_PROMOTION,
        )
        self.persist()
        logger.info("Exercise %s manually validated", ex_id)
        return True

    def increment_usage(self, ex_id: str):
        if ex_id in self._exercises:
            self._exercises[ex_id]["usage_count"] += 1
            self._auto_promote(ex_id)
            self.persist()

    def _auto_promote(self, ex_id: str):
        """Auto-validation by repeated usage."""
        ex = self._exercises[ex_id]
        if not ex.get("validated") and ex.get("usage_count", 0) >= MIN_USAGE_FOR_AUTO_PROMOTION:
            ex["validated"] = True
            logger.info("Exercise %s auto-promoted to validated (count=%d)", ex_id, ex["usage_count"])

    # ── Search ─────────────────────────────────────────────────────────────

    def search(
        self,
        concept: Optional[str] = None,
        difficulty: Optional[str] = None,
        min_usage: int = 0,
        validated_only: bool = False,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """Searches exercises by criteria."""
        results = []
        for ex in self._exercises.values():
            if concept and ex.get("concept") != concept:
                continue
            if difficulty and ex.get("difficulty") != difficulty:
                continue
            if ex.get("usage_count", 0) < min_usage:
                continue
            if validated_only and not ex.get("validated"):
                continue
            results.append(dict(ex))
        # Sort by descending usage_count
        results.sort(key=lambda x: x.get("usage_count", 0), reverse=True)
        return results[:limit]

    def list_pending(self) -> List[Dict[str, Any]]:
        """Unvalidated exercises (to review)."""
        return [dict(ex) for ex in self._exercises.values() if not ex.get("validated")]

    def stats(self) -> Dict[str, Any]:
        total = len(self._exercises)
        validated = sum(1 for ex in self._exercises.values() if ex.get("validated"))
        by_concept: Dict[str, int] = {}
        for ex in self._exercises.values():
            c = ex.get("concept", "unknown")
            by_concept[c] = by_concept.get(c, 0) + 1
        return {
            "total": total,
            "validated": validated,
            "pending": total - validated,
            "by_concept": by_concept,
        }
