"""
PedagogicalAgent – Pedagogical Agent (LLM-ready version).

Implements the ITS pedagogical model:
  • Scaffolding (gradual support)
  • Buggy Rule-based diagnosis
  • Adaptive feedback based on cognitive load

If an LLMClient is configured (API key present), messages are
 dynamically generated by the language model. Otherwise, fallback
 to static templates.
"""

from typing import Dict, Any, Optional
from core.llm_client import LLMClient


class PedagogicalAgent:
    """
    Decides the type and timing of the pedagogical intervention.
    """

    SCAFFOLD_LEVELS = [
        "subtle_hint",
        "guided_question",
        "partial_explanation",
        "full_explanation",
    ]

    def __init__(self, llm_client: Optional[LLMClient] = None):
        self.llm = llm_client
        self.current_scaffold_level = 0
        self.consecutive_errors = 0

    # ── Pedagogical decisions ───────────────────────────────────────────────

    async def decide_intervention(
        self,
        cognitive_load: dict,
        math_diagnostic: Optional[dict],
        student_profile: dict,
        exercise_context: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        load_level = cognitive_load.get("level", "low")
        buggy_rule = math_diagnostic.get("buggy_rule") if math_diagnostic else None
        match = math_diagnostic.get("match", False) if math_diagnostic else True

        intervention = {
            "type": "none",
            "message": None,
            "action": None,
        }

        # 1. High cognitive load → prioritize stress reduction
        if load_level == "high":
            msg = (
                "You seem to be working hard. Let's take a step back. "
                "Would you like a simpler hint?"
            )
            if self.llm and self.llm.is_available():
                msg = await self.llm.generate(
                    "The student seems stuck. Write ONE short, practical sentence offering a hint or asking if they need help. "
                    "Do NOT be overly empathetic or therapeutic. Be concise, direct, and friendly like a math tutor, not a counselor."
                )
            intervention["type"] = "cognitive_support"
            intervention["message"] = msg
            intervention["action"] = "offer_oral_mode"
            self.current_scaffold_level = 0
            return intervention

        # 2. Error with buggy rule detected → targeted feedback
        if not match and buggy_rule:
            self.consecutive_errors += 1
            msg = await self._buggy_rule_message(
                buggy_rule,
                math_diagnostic.get("hint", ""),
                math_diagnostic.get("user_ast", {}).get("content", ""),
            )
            intervention["type"] = "buggy_rule_feedback"
            intervention["message"] = msg
            intervention["action"] = "targeted_explanation"
            return intervention

        # 3. Medium load or inactivity → gradual hint
        if load_level == "medium" or cognitive_load.get("should_intervene"):
            msg = await self._scaffold_message(exercise_context=exercise_context)
            intervention["type"] = "scaffold"
            intervention["message"] = msg
            intervention["action"] = "hint"
            return intervention

        # 4. Success
        if match:
            self.consecutive_errors = 0
            self.current_scaffold_level = max(0, self.current_scaffold_level - 1)

        return intervention

    # ── Generated messages ──────────────────────────────────────────────────

    async def _scaffold_message(
        self, exercise_context: Optional[Dict[str, Any]] = None
    ) -> str:
        level = self.SCAFFOLD_LEVELS[
            min(self.current_scaffold_level, len(self.SCAFFOLD_LEVELS) - 1)
        ]

        # Exercise context (avoids generic off-topic hints)
        problem = "math exercise"
        current_step = None
        if exercise_context:
            problem = exercise_context.get("problem_latex", problem)
            steps = exercise_context.get("steps", [])
            # We could use progress info if available
            current_step = exercise_context.get("current_step_hint")

        # Static fallback (generic but we prefer the contextual LLM)
        fallback_map = {
            "subtle_hint": "Take a closer look at the current step. What can you simplify?",
            "guided_question": "What is the goal of the next operation?",
            "partial_explanation": "Try to isolate the unknown step by step.",
            "full_explanation": "Here is a hint: look at the structure of the equation and apply the inverse operation.",
        }
        fallback = fallback_map.get(level, fallback_map["subtle_hint"])

        if self.llm and self.llm.is_available():
            prompt = (
                f"The student is working on this math problem: {problem}\n"
                f"Provide a {level.replace('_', ' ')} to guide them.\n"
            )
            if current_step:
                prompt += f"They are currently at this step: {current_step}\n"
            prompt += (
                "IMPORTANT: The hint must be SPECIFIC to the problem above. "
                "Do NOT give generic advice about distributive property, factoring, "
                "or binomial expansion unless the problem explicitly involves those concepts. "
                "Keep it short (1-2 sentences)."
            )
            fallback = await self.llm.generate(prompt, temperature=0.5, max_tokens=200)

        if self.consecutive_errors > 1:
            self.current_scaffold_level = min(
                self.current_scaffold_level + 1, len(self.SCAFFOLD_LEVELS) - 1
            )

        return fallback

    async def _buggy_rule_message(
        self, rule_name: str, hint: str, student_answer: str
    ) -> str:
        fallback = (
            f"I noticed a common mistake: **{rule_name}**.\n"
            f"{hint}\n"
            "Try to redo the step keeping this in mind."
        )

        if self.llm and self.llm.is_available():
            fallback = await self.llm.explain_buggy_rule(
                rule_name=rule_name,
                rule_description=hint,
                student_answer=student_answer or "unknown",
            )

        return fallback

    def reset(self):
        self.current_scaffold_level = 0
        self.consecutive_errors = 0
